// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tracker.api.Data;

#nullable disable

namespace tracker.api.Migrations
{
    [DbContext(typeof(JobApplicationDbContext))]
    [Migration("20250313234826_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("tracker.api.Data.JobApplicationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AppliedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("StatusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("JobApplications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppliedDate = new DateTime(2025, 3, 2, 12, 43, 44, 586, DateTimeKind.Local).AddTicks(2832),
                            CompanyName = "Bulk Tea Importers",
                            Position = "Tea Lady",
                            StatusId = (byte)1
                        },
                        new
                        {
                            Id = 2,
                            AppliedDate = new DateTime(2025, 3, 2, 12, 43, 44, 587, DateTimeKind.Local).AddTicks(6989),
                            CompanyName = "Coca Cola NZ",
                            Position = "Taste Tester",
                            StatusId = (byte)1
                        },
                        new
                        {
                            Id = 3,
                            AppliedDate = new DateTime(2025, 3, 3, 12, 43, 44, 587, DateTimeKind.Local).AddTicks(7003),
                            CompanyName = "Griffens Food Company",
                            Position = "Packaging Assistents Assistent",
                            StatusId = (byte)1
                        },
                        new
                        {
                            Id = 4,
                            AppliedDate = new DateTime(2025, 3, 6, 12, 43, 44, 587, DateTimeKind.Local).AddTicks(7007),
                            CompanyName = "Sausage Roles R Us",
                            Position = "Personal Assistant",
                            StatusId = (byte)3
                        },
                        new
                        {
                            Id = 5,
                            AppliedDate = new DateTime(2025, 3, 6, 12, 43, 44, 587, DateTimeKind.Local).AddTicks(7008),
                            CompanyName = "Sausage Roles R Us",
                            Position = "Sales Manager",
                            StatusId = (byte)1
                        },
                        new
                        {
                            Id = 6,
                            AppliedDate = new DateTime(2025, 3, 6, 12, 43, 44, 587, DateTimeKind.Local).AddTicks(7012),
                            CompanyName = "Aunt Megs",
                            Position = "Gossip",
                            StatusId = (byte)1
                        },
                        new
                        {
                            Id = 7,
                            AppliedDate = new DateTime(2025, 3, 7, 12, 43, 44, 587, DateTimeKind.Local).AddTicks(7014),
                            CompanyName = "Kings Water",
                            Position = "Plumber",
                            StatusId = (byte)1
                        },
                        new
                        {
                            Id = 8,
                            AppliedDate = new DateTime(2025, 3, 7, 12, 43, 44, 587, DateTimeKind.Local).AddTicks(7016),
                            CompanyName = "Ashphalts Under Us",
                            Position = "Heavy Machinery Operator",
                            StatusId = (byte)2
                        },
                        new
                        {
                            Id = 9,
                            AppliedDate = new DateTime(2025, 3, 8, 12, 43, 44, 587, DateTimeKind.Local).AddTicks(7018),
                            CompanyName = "Driver Ed",
                            Position = "Driving Instructor",
                            StatusId = (byte)1
                        },
                        new
                        {
                            Id = 10,
                            AppliedDate = new DateTime(2025, 3, 9, 12, 43, 44, 587, DateTimeKind.Local).AddTicks(7020),
                            CompanyName = "Customs",
                            Position = "Drugs Detection Dog",
                            StatusId = (byte)1
                        },
                        new
                        {
                            Id = 11,
                            AppliedDate = new DateTime(2025, 3, 10, 12, 43, 44, 587, DateTimeKind.Local).AddTicks(7022),
                            CompanyName = "Shipping NZ",
                            Position = "Captain First Class",
                            StatusId = (byte)1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
